# Business Understanding

The Products table contains information about the products sold by AdventureWorks.

This dataset will be used to:

- Analyze product performance
- Measure revenue by product
- Analyze sales by category and subcategory
- Identify best-selling products
- Support Power BI dashboards

The table will later be linked with the Sales table using **ProductKey**.

# 1. Import Libraries and Load Dataset

In [56]:
import pandas as pd 
import numpy as np

products = pd.read_csv("C:/Users/singh/OneDrive/Desktop/AdventureWorks_Analytics/data/raw/AdventureWorks_Products.csv")

# 2. Data Profiling

In [57]:
products.head()
products.tail()

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
288,602,5,BB-8107,ML Bottom Bracket,ML Bottom Bracket,Aluminum alloy cups; large diameter spindle.,NaN,0,0,44.9506,101.24
289,603,5,BB-9108,HL Bottom Bracket,HL Bottom Bracket,Aluminum alloy cups and a hollow axle.,NaN,0,0,53.9416,121.49
290,604,2,BK-R19B-44,"Road-750 Black, 44",Road-750,Entry level adult bike; offers a comfortable r...,Black,44,U,343.6496,539.99
291,605,2,BK-R19B-48,"Road-750 Black, 48",Road-750,Entry level adult bike; offers a comfortable r...,Black,48,U,343.6496,539.99
292,606,2,BK-R19B-52,"Road-750 Black, 52",Road-750,Entry level adult bike; offers a comfortable r...,Black,52,U,343.6496,539.99

In [58]:
products.shape

(293, 11)

In [59]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293 entries, 0 to 292
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ProductKey             293 non-null    int64
 1   ProductSubcategoryKey  293 non-null    int64
 2   ProductSKU             293 non-null    object
 3   ProductName            293 non-null    object
 4   ModelName              293 non-null    object
 5   ProductDescription     293 non-null    object
 6   ProductColor           243 non-null    object
 7   ProductSize            293 non-null    object
 8   ProductStyle           293 non-null    object
 9   ProductCost            293 non-null    float64
 10  ProductPrice           293 non-null    float64
dtypes: float64(2), int64(2), object(7)
memory usage: 25.3+ KB

In [60]:
products.isnull().sum()

ProductKey                0
ProductSubcategoryKey     0
ProductSKU                0
ProductName               0
ModelName                 0
ProductDescription        0
ProductColor             50
ProductSize               0
ProductStyle              0
ProductCost               0
ProductPrice              0
dtype: int64

In [61]:
products.duplicated().sum()

np.int64(0)

In [62]:
products.describe()

       ProductKey  ProductSubcategoryKey  ProductCost  ProductPrice
count  293.000000             293.000000   293.000000    293.000000
mean   441.552901              12.283276   413.661009    714.437357
std    108.064327               9.892831   517.611849    872.157258
min    214.000000               1.000000     0.856500      2.290000
25%    354.000000               2.000000    31.724400     63.500000
50%    457.000000              12.000000   199.375700    333.420000
75%    533.000000              17.000000   601.743700   1003.910000
max    606.000000              37.000000  2171.294200   3578.270000

In [63]:
products.nunique()

ProductKey               293
ProductSubcategoryKey     37
ProductSKU               293
ProductName              293
ModelName                119
ProductDescription       115
ProductColor               9
ProductSize               19
ProductStyle               4
ProductCost              111
ProductPrice             107
dtype: int64

In [64]:
products["ProductColor"].value_counts(dropna=False)

ProductColor
Black           88
NaN             50
Red             37
Silver          36
Yellow          36
Blue            26
Multi            8
Silver/Black     7
White            4
Grey             1
Name: count, dtype: int64

In [65]:
products["ProductSize"].value_counts(dropna=False)

ProductSize
0     84
44    29
48    25
52    16
42    15
58    13
38    12
L     11
40    11
62    11
M     11
60    11
46    11
50     9
54     9
S      9
XL     3
56     2
70     1
Name: count, dtype: int64

In [66]:
products["ProductStyle"].value_counts(dropna=False)

ProductStyle
U    174
0     84
W     28
M      7
Name: count, dtype: int64

In [67]:
products["ModelName"].value_counts(dropna=False)

ModelName
LL Road Frame         12
Road-650              12
Mountain-500          10
LL Touring Frame      10
LL Mountain Frame     10
                      ..
Touring Rear Wheel     1
HL Road Rear Wheel     1
ML Road Rear Wheel     1
LL Road Rear Wheel     1
HL Bottom Bracket      1
Name: count, Length: 119, dtype: int64

In [68]:
products.dtypes

ProductKey                 int64
ProductSubcategoryKey      int64
ProductSKU                object
ProductName               object
ModelName                 object
ProductDescription        object
ProductColor              object
ProductSize               object
ProductStyle              object
ProductCost              float64
ProductPrice             float64
dtype: object

# 3. Data Quality Assessment

- Missing values found in **ProductColor (50)**.
- No duplicate records found.
- No inconsistent values detected.
- No datatype conversion required.

**Conclusion:** The dataset is in good condition and requires only minor cleaning before analysis.

# 4. Data Cleaning

In [69]:
products.columns = (
    products.columns
    .str.strip()
    .str.replace(" ","_")
    .str.replace(r'(?<!^)(?=[A-Z])',"_",regex=True)
    .str.lower()
)

In [70]:
products.columns

Index(['product_key', 'product_subcategory_key', 'product_s_k_u',
       'product_name', 'model_name', 'product_description', 'product_color',
       'product_size', 'product_style', 'product_cost', 'product_price'],
      dtype='object')

In [71]:
products = products.rename(columns={'product_s_k_u':'product_sku'})

In [72]:
products['product_color']= products['product_color'].fillna('Unknown')

In [73]:
products.isnull().sum()

product_key                0
product_subcategory_key    0
product_sku                0
product_name               0
model_name                 0
product_description        0
product_color              0
product_size               0
product_style              0
product_cost               0
product_price              0
dtype: int64

In [74]:
text_columns = products.select_dtypes(include='object').columns

for col in text_columns:
    products[col]=products[col].str.strip()

In [79]:
products.columns

Index(['product_key', 'product_subcategory_key', 'product_sku', 'product_name',
       'model_name', 'product_description', 'product_color', 'product_size',
       'product_style', 'product_cost', 'product_price'],
      dtype='object')

# 5. Export Clean Dataset

In [75]:
products.to_csv("C:/Users/singh/OneDrive/Desktop/AdventureWorks_Analytics/data/cleaned/products_clean.csv"
                ,index=False
                )

In [84]:
(products['product_size'].str.len() >10).sum()

np.int64(0)