#  Business Understanding

The Product Categories table contains the main product categories offered by AdventureWorks.

This table is used to classify products into high-level business categories and supports category-level sales analysis.

It will later be connected to the Products table through the ProductSubcategories table.

# 1. Load the Dataset

In [24]:
import pandas as pd 
import numpy as np

categories = pd.read_csv("C:/Users/singh/OneDrive/Desktop/AdventureWorks_Analytics/data/raw/AdventureWorks_Product_Categories.csv")

# 2. Data Profiling

In [25]:
categories.head()
categories.tail()

   ProductCategoryKey CategoryName
0                   1        Bikes
1                   2   Components
2                   3     Clothing
3                   4  Accessories

In [26]:
categories.shape

(4, 2)

# 3. Data Quality Assessment

- No missing values found.
- No duplicate records found.
- No datatype issues identified.
- No inconsistent values detected.
- Column names will be standardized to `snake_case` for consistency across the project.

**Conclusion:** The Product Categories dataset is clean and requires only minor formatting before loading into the ETL pipeline.

# 4. Data Cleaning

In [27]:
categories.head()

   ProductCategoryKey CategoryName
0                   1        Bikes
1                   2   Components
2                   3     Clothing
3                   4  Accessories

In [28]:
categories.columns = categories.columns.str.strip()

In [29]:
categories.columns = [
    'product_category_key',
    'category_name'               
 ]

In [30]:
categories.dtypes

product_category_key     int64
category_name           object
dtype: object

In [31]:
categories['category_name'] = categories['category_name'].str.strip().str.title()

# 5. Export Clean Dataset

In [32]:
categories.to_csv("C:/Users/singh/OneDrive/Desktop/AdventureWorks_Analytics/data/cleaned/categories_clean.csv"
                  ,index=False
 )